; Custom PHP configuration
upload_max_filesize = 100M
post_max_size = 100M
memory_limit = 256M
max_execution_time = 300
date.timezone = Asia/Manila
display_errors = On
error_reporting = E_ALL
session.save_handler = redis
session.save_path = tcp://redis:6379
